(function(){"use strict";
const ORG_FALLBACK="cms9eoh7c0000prxue4fvntqp";
const defaults={homepage:{aboutPanelLabel:"What is\nThe Harmonia\nProject",connectPanelLabel:"Connect",upcomingPanelLabel:"Upcoming",galleryPanelLabel:"Gallery"},about:{title:"What is The Harmonia Project",paragraph1:"The Harmonia Project is a philanthropic initiative dedicated to fostering greater community harmony. In a time of increasing division, we believe meaningful progress begins by finding common ground, encouraging understanding, and bringing people together around shared values and shared purpose.",paragraph2:"Each year, the Harmonia Project focuses on a pressing issue affecting our communities. Through dialogue, education, service, advocacy, and collaborative action, we strive to create lasting, positive change while empowering individuals to become active leaders and engaged citizens.",paragraph3:"Our mission is rooted in the belief that lasting harmony is not achieved through agreement alone, but through respectful conversation, genuine connection, and collective action."},connect:{title:"Connection is where change begins.",paragraph1:"The Harmonia Project exists because meaningful progress starts when people choose to listen, collaborate, and act together. Whether you're an individual with an idea, a nonprofit seeking a partner, a business looking to give back, or someone searching for a way to make a difference, we'd love to hear from you.",paragraph2:"Every conversation has the potential to spark a new initiative, every partnership can strengthen a community, and every person has something valuable to contribute."}};
const org=()=>window.HarmoniaApi.getOrganizationId()||ORG_FALLBACK;
const req=(key,opt={})=>window.HarmoniaApi.request(`/site-content/${encodeURIComponent(key)}?organizationId=${encodeURIComponent(org())}`,opt);
const val=id=>document.getElementById(id)?.value?.trim()||"";const put=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v||""};
const status=(key,msg,bad=false)=>{const e=document.getElementById(`${key}EditorStatus`);if(e){e.textContent=msg;e.classList.toggle('error',bad)}};
async function load(key){const r=await req(key);return {...(defaults[key]||{}),...(r.data||{})};}
async function publish(key,data){return req(key,{method:'PUT',body:JSON.stringify({data})});}
async function hydrate(key){try{status(key,'Loading…');const d=await load(key);if(key==='homepage'){put('homepageAboutLabel',d.aboutPanelLabel);put('homepageConnectLabel',d.connectPanelLabel);put('homepageUpcomingLabel',d.upcomingPanelLabel);put('homepageGalleryLabel',d.galleryPanelLabel)}if(key==='about'){put('aboutEditorTitle',d.title);put('aboutEditorParagraph1',d.paragraph1);put('aboutEditorParagraph2',d.paragraph2);put('aboutEditorParagraph3',d.paragraph3)}if(key==='connect'){put('connectEditorTitle',d.title);put('connectEditorParagraph1',d.paragraph1);put('connectEditorParagraph2',d.paragraph2)}status(key,'Ready to publish.')}catch(e){status(key,e.message,true)}}
async function save(key){let data;if(key==='homepage')data={aboutPanelLabel:val('homepageAboutLabel'),connectPanelLabel:val('homepageConnectLabel'),upcomingPanelLabel:val('homepageUpcomingLabel'),galleryPanelLabel:val('homepageGalleryLabel')};if(key==='about')data={title:val('aboutEditorTitle'),paragraph1:val('aboutEditorParagraph1'),paragraph2:val('aboutEditorParagraph2'),paragraph3:val('aboutEditorParagraph3')};if(key==='connect')data={title:val('connectEditorTitle'),paragraph1:val('connectEditorParagraph1'),paragraph2:val('connectEditorParagraph2')};try{status(key,'Publishing…');await publish(key,data);status(key,'Published successfully.')}catch(e){status(key,e.message,true)}}
async function publishGallery(){const items=(window.HarmoniaGallery?.getAll?.()||window.HarmoniaGallery?.getAllGalleryItems?.()||[]).filter(x=>x.visibility!=='private').map(x=>({title:x.title,description:x.description,imageUrl:window.HarmoniaGallery?.resolveImageUrl?.(x)||x.imageUrl||'',altText:x.altText,photographer:x.photographer,eventName:x.eventName,location:x.location,dateTaken:x.dateTaken,featured:!!x.featured}));await publish('gallery',{title:'Moments of connection.',items});alert(`Published ${items.length} gallery item(s).`)}
async function publishPartners(){const items=(window.HarmoniaPartners?.getAll?.()||[]).filter(x=>String(x.status||'active').toLowerCase()==='active').map(x=>({name:x.name,description:x.description||x.notes||'',website:x.website||'',sector:x.sector||x.type||'',location:x.address||x.location||''}));await publish('partners',{title:'Organizations building harmony with us.',items});alert(`Published ${items.length} partner(s).`)}
function initialize(){for(const key of ['homepage','about','connect']){const b=document.getElementById(`${key}PublishButton`);if(b&&!b.dataset.ready){b.dataset.ready='1';b.addEventListener('click',()=>save(key))}hydrate(key)}document.getElementById('publishGalleryButton')?.addEventListener('click',publishGallery);document.getElementById('publishPartnersButton')?.addEventListener('click',publishPartners);console.log('✅ Website publishing initialized')}
window.initializeSiteContentEditors=initialize;window.HarmoniaSiteContent={load,publish,publishGallery,publishPartners};})();