(function(){
"use strict";
let editingFileId=null,activeFileProjectId=null,pendingFile=null;
function el(){return{modal:document.getElementById('fileModal'),title:document.getElementById('fileModalTitle'),titleInput:document.getElementById('fileTitleInput'),categoryInput:document.getElementById('fileCategoryInput'),sourceInput:document.getElementById('fileSourceInput'),urlInput:document.getElementById('fileUrlInput'),uploadInput:document.getElementById('fileUploadInput'),descriptionInput:document.getElementById('fileDescriptionInput'),pinnedInput:document.getElementById('filePinnedInput'),linkFields:document.getElementById('fileLinkFields'),uploadFields:document.getElementById('fileUploadFields'),selectedName:document.getElementById('selectedFileName'),save:document.getElementById('saveFileButton')}}
function sourceFields(){const x=el(),upload=x.sourceInput?.value==='upload';if(x.linkFields)x.linkFields.hidden=upload;if(x.uploadFields)x.uploadFields.hidden=!upload;}
function close(){const x=el();if(x.modal)x.modal.hidden=true;editingFileId=null;activeFileProjectId=null;pendingFile=null;}
function open(data=null,options={}){const x=el();if(!x.modal)return;editingFileId=data?.id||null;activeFileProjectId=data?.projectId??options.projectId??null;pendingFile=null;if(x.title)x.title.textContent=data?'Edit File':'Add File';if(x.titleInput)x.titleInput.value=data?.title||data?.originalName||'';if(x.categoryInput)x.categoryInput.value=data?.category||'document';if(x.sourceInput)x.sourceInput.value=data?.sourceType||'upload';if(x.urlInput)x.urlInput.value=data?.url||'';if(x.descriptionInput)x.descriptionInput.value=data?.description||'';if(x.pinnedInput)x.pinnedInput.checked=Boolean(data?.pinned);if(x.uploadInput)x.uploadInput.value='';if(x.selectedName)x.selectedName.textContent='No file selected';sourceFields();x.modal.hidden=false;x.titleInput?.focus();}
async function save(){const x=el();const title=x.titleInput?.value.trim()||'';const sourceType=x.sourceInput?.value||'upload';if(!title){alert('Please enter a file title.');return;}const data={title,category:x.categoryInput?.value||'document',sourceType,url:x.urlInput?.value.trim()||'',description:x.descriptionInput?.value.trim()||'',pinned:Boolean(x.pinnedInput?.checked),projectId:activeFileProjectId,file:pendingFile};try{if(editingFileId)await window.HarmoniaFiles.update(editingFileId,data);else await window.HarmoniaFiles.add(data);close();window.renderFiles?.();}catch(e){alert(e.message||'File could not be saved.');}}
function init(){const x=el();if(!x.modal)return;document.querySelectorAll('[data-close-file-modal]').forEach(b=>{if(!b.dataset.v1){b.addEventListener('click',close);b.dataset.v1='1';}});if(x.sourceInput&&!x.sourceInput.dataset.v1){x.sourceInput.addEventListener('change',sourceFields);x.sourceInput.dataset.v1='1';}if(x.uploadInput&&!x.uploadInput.dataset.v1){x.uploadInput.addEventListener('change',()=>{pendingFile=x.uploadInput.files?.[0]||null;if(x.selectedName)x.selectedName.textContent=pendingFile?.name||'No file selected';if(pendingFile&&!x.titleInput.value)x.titleInput.value=pendingFile.name;});x.uploadInput.dataset.v1='1';}if(x.save&&!x.save.dataset.v1){x.save.addEventListener('click',save);x.save.dataset.v1='1';}sourceFields();}
window.openFileModal=open;window.closeFileModal=close;window.initializeFileModal=init;console.log('✅ Live Files Modal Loaded');
})();
