(function(){
"use strict";
let activeTaskFilter='all';
function dateText(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d)?'':d.toLocaleDateString('en-US',{month:'short',day:'numeric'});}
function tasks(){return window.HarmoniaWork?.getAll?.()||[];}
function filtered(){return tasks().filter(t=>activeTaskFilter==='all'||(activeTaskFilter==='completed'&&t.status==='done')||(activeTaskFilter==='open'&&t.status!=='done')||(activeTaskFilter==='high'&&t.priority==='high'));}
function renderTasks(){const list=document.getElementById('focusList'),empty=document.getElementById('taskEmptyState');if(!list)return;const visible=filtered().slice(0,8);list.innerHTML='';empty.hidden=visible.length>0;for(const t of visible){const a=document.createElement('article');a.className='focus-item';a.innerHTML=`<div><strong></strong><small></small></div><span class="priority-badge ${t.priority||'medium'}"></span>`;a.querySelector('strong').textContent=t.title||'Untitled task';a.querySelector('small').textContent=[t.project?.name||t.projectTitle||'',dateText(t.dueDate)].filter(Boolean).join(' · ')||'No due date';a.querySelector('span').textContent=t.priority||'medium';a.addEventListener('click',()=>{window.openAdminPage?.('work');window.openWorkEditor?.(t.id);});list.appendChild(a);}}
function renderEvents(){const box=document.querySelector('.event-preview-list');if(!box)return;const events=(window.HarmoniaEvents?.getAll?.()||[]).filter(e=>e.startDate&&new Date(`${e.startDate}T23:59:59`)>=new Date()).sort((a,b)=>a.startDate.localeCompare(b.startDate)).slice(0,3);box.innerHTML='';for(const e of events){const d=new Date(`${e.startDate}T00:00:00`),a=document.createElement('article');a.className='event-preview';a.innerHTML='<div class="event-date-block"><span></span><strong></strong></div><div><h4></h4><p></p></div><span class="status-badge published"></span>';a.querySelector('.event-date-block span').textContent=d.toLocaleString('en-US',{month:'short'}).toUpperCase();a.querySelector('.event-date-block strong').textContent=String(d.getDate()).padStart(2,'0');a.querySelector('h4').textContent=e.title;a.querySelector('p').textContent=[e.location,e.startTime].filter(Boolean).join(' · ')||'Details pending';a.querySelector('.status-badge').textContent=e.status||'planning';box.appendChild(a);}}
function renderStatus(){const values=document.querySelectorAll('.status-list strong');if(values[0])values[0].textContent=String((window.HarmoniaEvents?.getAll?.()||[]).filter(e=>e.startDate&&new Date(e.startDate)>=new Date(new Date().toDateString())).length);if(values[2])values[2].textContent=String((window.HarmoniaPartners?.getAll?.()||[]).length);}
function render(){renderTasks();renderEvents();renderStatus();}
function initializeDashboard(){const date=document.getElementById('dashboardDate');if(date)date.textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});const f=document.getElementById('taskFilter');if(f&&!f.dataset.live){f.addEventListener('change',()=>{activeTaskFilter=f.value;renderTasks();});f.dataset.live='1';}document.getElementById('addTaskButton')?.addEventListener('click',()=>{window.openAdminPage?.('work');window.openWorkEditor?.();});render();}
for(const e of ['harmonia:work-updated','harmonia:events-updated','harmonia:partners-updated'])document.addEventListener(e,render);
window.renderDashboard=render;window.renderTasks=renderTasks;window.initializeDashboard=initializeDashboard;console.log('✅ Live Dashboard Loaded');
})();
