ALTER TABLE "SitePage"
ADD COLUMN IF NOT EXISTS "draftData" JSONB;

ALTER TABLE "SitePage"
ADD COLUMN IF NOT EXISTS "draftUpdatedAt" TIMESTAMP(3);

ALTER TABLE "SitePage"
ADD COLUMN IF NOT EXISTS "publishedVersion" INTEGER NOT NULL DEFAULT 0;
