(function(){"use strict";
const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);
let mine=null;
function editor(){const by=new Map((mine?.weekly||[]).map(x=>[Number(x.dayOfWeek),x]));return `<section class="admin-card"><h3>My availability</h3><p>Keep this lightweight and realistic. It helps Harmonia avoid unnecessary scheduling messages.</p><form id="adminAvailabilityForm"><div class="availability-week-grid">${days.map((d,i)=>{const x=by.get(i);return `<div class="availability-day-row"><label><input type="checkbox" name="day-${i}" ${x?'checked':''}> ${d}</label><input type="time" name="start-${i}" value="${x?.startTime||'09:00'}"><span>to</span><input type="time" name="end-${i}" value="${x?.endTime||'17:00'}"></div>`}).join('')}</div><div class="availability-fields"><label>Preferred hours/week<input type="number" min="0" max="80" name="preferredHoursPerWeek" value="${mine?.preferredHoursPerWeek||0}"></label><label>Commitment<select name="commitmentLevel"><option value="CASUAL">Occasional</option><option value="REGULAR" ${mine?.commitmentLevel==='REGULAR'?'selected':''}>Regular</option><option value="LEADERSHIP" ${mine?.commitmentLevel==='LEADERSHIP'?'selected':''}>Leadership</option></select></label></div><label>Notes<textarea name="schedulingNotes" maxlength="500">${esc(mine?.schedulingNotes||'')}</textarea></label><label><input type="checkbox" name="isOpenToOpportunities" ${mine?.isOpenToOpportunities!==false?'checked':''}> Open to matching opportunities</label><button class="primary-button" type="submit">Save availability</button><span id="availabilityStatus"></span></form></section>`}
async function save(e){e.preventDefault();const f=e.currentTarget,weekly=[];for(let i=0;i<7;i++)if(f.elements[`day-${i}`].checked)weekly.push({dayOfWeek:i,startTime:f.elements[`start-${i}`].value,endTime:f.elements[`end-${i}`].value});const status=document.getElementById('availabilityStatus');status.textContent='Saving…';try{mine=await window.HarmoniaApi.request('/users/me/availability',{method:'PATCH',body:JSON.stringify({weekly,exceptions:mine?.exceptions||[],preferredHoursPerWeek:Number(f.preferredHoursPerWeek.value||0),commitmentLevel:f.commitmentLevel.value,schedulingNotes:f.schedulingNotes.value,isOpenToOpportunities:f.isOpenToOpportunities.checked,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Chicago'})});status.textContent='Saved.'}catch(err){status.textContent=err.message||'Could not save'}}
async function search(){const q=new URLSearchParams();for(const [id,key] of [['availabilityDay','dayOfWeek'],['availabilityStart','startTime'],['availabilityEnd','endTime']]){const v=document.getElementById(id)?.value;if(v)q.set(key,v)}const rows=await window.HarmoniaApi.request(`/users/availability?${q}`);document.getElementById('availabilityDirectory').innerHTML=rows.map(p=>`<article class="availability-person-card"><div><strong>${esc(p.user.firstName)} ${esc(p.user.lastName)}</strong><span>${esc(p.user.email)}</span></div><span>${p.preferredHoursPerWeek||0} hrs/week · ${esc(p.commitmentLevel.toLowerCase())}</span><p>${esc(p.schedulingNotes||'No scheduling note')}</p><small>${p.weekly.map(w=>`${days[w.dayOfWeek]} ${w.startTime}–${w.endTime}`).join(' · ')||'No recurring windows'}</small></article>`).join('')||'<p class="empty-state">No people match that time.</p>'}
async function initializeAvailabilityPage(){const page=document.getElementById('availability');if(!page)return;mine=await window.HarmoniaApi.request('/users/me/availability');document.getElementById('availabilitySelf').innerHTML=editor();document.getElementById('adminAvailabilityForm').addEventListener('submit',save);const owner=window.HarmoniaAuth?.getCurrentUser?.()?.role==='SUPER_ADMIN';document.getElementById('availabilityDirectoryPanel').hidden=!owner;if(owner){document.getElementById('availabilitySearchButton').addEventListener('click',search);await search()}}
window.initializeAvailabilityPage=initializeAvailabilityPage;window.renderAvailabilityPage=initializeAvailabilityPage;})();
