(function(){"use strict";
let data={summary:{},people:[]},drafts=[];
const $=id=>document.getElementById(id);
function isOwner(){return window.HarmoniaAuth?.getCurrentUser?.()?.role==="SUPER_ADMIN"}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c])}
function consent(p){const items=[];if(p.newsletterOptIn)items.push("Newsletter");if(p.eventUpdatesOptIn)items.push("Events");if(p.volunteerUpdatesOptIn)items.push("Volunteer");if(p.partnerUpdatesOptIn)items.push("Partners");if(p.marketingUnsubscribedAt)return '<span class="audience-unsubscribed">Unsubscribed</span>';return items.length?items.map(i=>`<span class="audience-opted">${i}</span>`).join(" "):"None"}
function render(){const s=data.summary||{};$("audienceSummary").innerHTML=[['totalAccounts','Total accounts'],['newsletterSubscribers','Newsletter'],['eventSubscribers','Event updates'],['volunteerSubscribers','Volunteer'],['unsubscribed','Unsubscribed'],['newThisMonth','New this month']].map(([k,l])=>`<article><strong>${s[k]||0}</strong><span>${l}</span></article>`).join("");$("audienceTableBody").innerHTML=(data.people||[]).map(p=>`<tr><td><strong>${esc(p.firstName)} ${esc(p.lastName)}</strong><small>${esc(p.email)}</small></td><td>${consent(p)}</td><td>${esc((p.interests||[]).map(i=>i.replaceAll("-"," ")).join(", ")||"—")}</td><td>${new Date(p.createdAt).toLocaleDateString()}</td></tr>`).join("")||'<tr><td colspan="4">No people match this view.</td></tr>'}
function renderDrafts(){$("campaignDraftList").innerHTML=drafts.map(d=>`<article class="campaign-draft-card"><div><strong>${esc(d.name)}</strong><small>${esc(d.audienceType.replaceAll("_"," "))} · ${d.recipientCount} recipients</small></div><span>${new Date(d.updatedAt).toLocaleDateString()}</span><p>${esc(d.subject)}</p></article>`).join("")||'<p class="empty-state">No campaign drafts yet.</p>'}
async function load(){if(!isOwner())return;const segment=$("audienceSegment")?.value||"ALL",search=$("audienceSearch")?.value||"";data=await window.HarmoniaApi.request(`/users/audience?segment=${encodeURIComponent(segment)}&search=${encodeURIComponent(search)}`);drafts=await window.HarmoniaApi.request('/users/campaign-drafts');render();renderDrafts()}
function filters(){return ($("campaignDraftForm")?.elements.interestFilters.value||"").split(",").map(v=>v.trim()).filter(Boolean)}
async function preview(){const type=$("campaignAudienceType")?.value;if(!type)return;const result=await window.HarmoniaApi.request(`/users/audience/preview?audienceType=${encodeURIComponent(type)}&interests=${encodeURIComponent(filters().join(","))}`);$("campaignRecipientCount").textContent=result.recipientCount||0}
function exportCsv(){const rows=[["First name","Last name","Email","Newsletter","Events","Volunteer","Partners","Interests","Joined"],...(data.people||[]).map(p=>[p.firstName,p.lastName,p.email,p.newsletterOptIn,p.eventUpdatesOptIn,p.volunteerUpdatesOptIn,p.partnerUpdatesOptIn,(p.interests||[]).join("|"),p.createdAt])];const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`harmonia-audience-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function saveDraft(e){e.preventDefault();const form=e.currentTarget,status=$("campaignDraftStatus");status.textContent="Saving…";try{const body={name:form.elements.name.value,subject:form.elements.subject.value,body:form.elements.body.value,audienceType:form.elements.audienceType.value,interestFilters:filters()};await window.HarmoniaApi.request('/users/campaign-drafts',{method:'POST',body:JSON.stringify(body)});status.textContent="Campaign draft saved. Nothing was sent.";form.reset();await load();await preview()}catch(err){status.textContent=err.message||"Could not save draft"}}
async function initializeAudiencePage(){const nav=document.querySelector('[data-page="audience"]'),page=$("audience");if(!nav||!page)return;nav.hidden=!isOwner();if(!isOwner())return;$("audienceSegment")?.addEventListener("change",load);let timer;$("audienceSearch")?.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(load,250)});$("audienceExport")?.addEventListener("click",exportCsv);$("campaignAudienceType")?.addEventListener("change",preview);$("campaignDraftForm")?.elements.interestFilters?.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(preview,250)});$("campaignDraftForm")?.addEventListener("submit",saveDraft);await load();await preview()}
window.initializeAudiencePage=initializeAudiencePage;window.renderAudiencePage=load;})();